<a href="https://colab.research.google.com/github/smoothbear/big_data/blob/main/1.Start.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Create

### Using NumPy's variety functions

#### ```np.array()```

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])

print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

a

<class 'numpy.ndarray'>
1
(6,)
6
int64


array([1, 2, 3, 4, 5, 6])

#### ```np.arange()```


In [ ]:
np.arange(1, 22, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [ ]:
np.arange(1, 22, 2) ** 2

array([  1,   9,  25,  49,  81, 121, 169, 225, 289, 361, 441])

### Using Timeit

In [ ]:
n = 100
print(timeit.timeit(f'x = [i**2 for i in range({n})]'))
print(timeit.timeit(f'x = np.arange({n})**2', setup='import numpy as np'))

24.21294088800005
1.6875411890000578


#### Indexing and Slicing

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[2][:]

array([ 9, 10, 11, 12])

In [ ]:
a[:, 0]

array([1, 5, 9])

#### Deep Copy

In [ ]:
b = a.copy()

print(a)
print(b)

[[ 1  1  3  4]
 [ 5  1  7  8]
 [ 9  1 11 12]]
[[ 1  2  3  4]
 [ 5  2  7  8]
 [ 9  2 11 12]]


#### Condition

In [ ]:
seven_up = a > 7
seven_ar = a[seven_up]

In [ ]:
condition_1 = a > 4
condition_2 = a < 10

a[condition_1 & condition_2]

array([6, 5, 6, 7, 8, 9, 6])

### Sort

In [ ]:
a1 = np.array([[1, 1], [2, 2]])
b1 = np.array([[3, 3], [4, 4]])

a1
b1

array([[3, 3],
       [4, 4]])