<a href="https://colab.research.google.com/github/smoothbear/big_data/blob/main/3.Numpy_quiz_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Create

## 0 1 

In [ ]:
import numpy as np

2*2 integers 다차원 배열을 초기화 하지 않은 상태로 생성하세요.

In [ ]:
array = np.empty((2, 2), int)
array

array([[     94596416104512, 7955898299855142912],
       [  36717586921579876, 7236828785387634688]])

크기가 10인 단위행렬을 생성하세요.

In [ ]:
array = np.eye(10)
array

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

모든 원소가 0으로 채워진 3*2 정수형 다차원 배열을 생성하세요.

In [ ]:
array = np.zeros((3, 2), dtype=int)
array

array([[0, 0],
       [0, 0],
       [0, 0]])

x = [0, 1, 2, 3] 정수형 배열 일 때,

x와 동일한 shape의 영행렬을 생성하세요.

In [ ]:
x=[0,1,2,3]
array = np.zeros_like(x)
array

array([0, 0, 0, 0])

모든 원소가 1로 채워진 4*3 실수형 다차원 배열을 생성하세요.

In [ ]:
array = np.ones((4, 3), dtype=float)
array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

x = [0, 1, 2, 3] 정수형 배열 일 때,

X와 동일한 shape를 가지고 모든 원소가 1인 다차원 배열을 생성하세요.

In [ ]:
x = [0, 1, 2, 3]
array = np.ones_like(x)
array

array([1, 1, 1, 1])

모든 원소가 6으로 채워진 2*5 uint형(부호없는 정수) 다차원 배열을 생성하세요.

In [ ]:
array = np.full((2, 5), 6, dtype="uint")
array

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint64)

x = [0, 1, 2, 3] 정수형 배열 일 때,


x와 동일한 shape이고 모든 원소가 6인 다차원 배열을 생성하세요.

In [ ]:
x = [0, 1, 2, 3]
array = np.full_like(x, 6)
array

array([6, 6, 6, 6])

array([6, 6, 6, 6])

## From existing data

ndarray [1, 2, 3] 배열을 생성하세요

In [ ]:
array = np.array([1, 2, 3])
array

array([1, 2, 3])

x = [1, 2] 일 때(python list 상태)

x를 `float`형 배열로 변환하세요.(numpy ndarray)

In [ ]:
x = [1, 2]
array = np.array(x, dtype=float)
array

array([1., 2.])

다시 Python List로 변환하세요

In [ ]:
array.tolist()

[1.0, 2.0]

## Numerical ranges

2, 4, 6, 8, ..., 100 을 원소로 가지는 배열을 생성하세요.

In [ ]:
array = np.array(range(2, 101, 2))
array

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

리스트 내포를 사용하여 1 ~ 100 자연수 중에 3 또는 4의 배수를 출력하시오

In [ ]:
array = [i for i in range(100) if (i % 3 == 0 or i % 4 == 0)]
array

[0,
 3,
 4,
 6,
 8,
 9,
 12,
 15,
 16,
 18,
 20,
 21,
 24,
 27,
 28,
 30,
 32,
 33,
 36,
 39,
 40,
 42,
 44,
 45,
 48,
 51,
 52,
 54,
 56,
 57,
 60,
 63,
 64,
 66,
 68,
 69,
 72,
 75,
 76,
 78,
 80,
 81,
 84,
 87,
 88,
 90,
 92,
 93,
 96,
 99]

3.0 에서 10.0 까지 50개의 원소가 균일하게 분포된 1차원 배열을 생성하세요.

In [ ]:
array = np.linspace(3.0, 10.0)
array

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

#Indexing and Slicing

msprint

1. shape(2,2,3) 그려보세요

2. shape(1,2,3,4) 그려보세요

In [ ]:
aa = [[1,2,3,4],[1,2,3,4], [1,2,3,4]]
array = np.array(aa).reshape(2,2,3)
array

array([[[1, 2, 3],
        [4, 1, 2]],

       [[3, 4, 1],
        [2, 3, 4]]])

In [ ]:
np.arange(24).reshape(1,2,3,4)

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]])

배열 x에 1부터 50까지의 (5,2,2) 배열을 생성하시오.

In [ ]:
array=np.array(range(1, 51)).reshape(5,5,2)
array

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]],

       [[31, 32],
        [33, 34],
        [35, 36],
        [37, 38],
        [39, 40]],

       [[41, 42],
        [43, 44],
        [45, 46],
        [47, 48],
        [49, 50]]])


x 배열이 10~100까지의 실수 중 5의 배수 일 때,

3차원 배열인 x를 생성하세요.

In [ ]:
array = np.array(range(10, 100, 5)).reshape(2, 3, 3)
array

array([[[10, 15, 20],
        [25, 30, 35],
        [40, 45, 50]],

       [[55, 60, 65],
        [70, 75, 80],
        [85, 90, 95]]])

위의 x에서 10이상 20미만을 인덱싱하시오.

In [ ]:
array[(array >= 10) & (array < 20)]

array([10, 15])

array([[[10, 15, 20],
        [25, 30, 35],
        [40, 45, 50]],

       [[55, 60, 65],
        [70, 75, 80],
        [85, 90, 95]]])

Q1. 

x가 10x10x3의 다차원 배열일때,

x의 두번째 차원이 150인 2차원 배열이 되도록 reshape하세요.

In [ ]:
np.ones([10,10,3]).reshape(10, 10, 3).reshape(2, 150)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.,

Q2. 

x = [[1, 2, 3], [4, 5, 6]] 일 때,

[1, 2, 3, 4, 5, 6]로 변환하세요.

In [ ]:
x = np.array([[1,2,3], [4,5,6])

array([1, 2, 3, 4, 5, 6])

In [ ]:
x = np.

array([1, 2, 3, 4, 5, 6])

Q3. 

x = [[1, 2, 3], [4, 5, 6]]

y = [[7, 8, 9], [10, 11, 12]] 일 때,

x와 y를 연결해서 [[1, 2, 3, 7, 8, 9], [4, 5, 6, 10, 11, 12]]를 만드세요


In [130]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[7,8,9], [10,11,12]])

a = np.concatenate((x, y), 1)
a

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Q4. 

x = [0, 1, 2]일 때, 

[0, 0, 1, 1, 2, 2]를 생성하세요.

In [ ]:
x = [0,1,2]
x = np.array(x+x)
x.sort()
x

array([0, 0, 1, 1, 2, 2])

array([0, 0, 1, 1, 2, 2])

Q5.

x = [0, 0, 0, 1, 2, 3, 0, 2, 1, 0]일 때,

앞, 뒤의 0을 제거하세요.

In [ ]:
x = [0, 0, 0, 1, 2, 3, 0, 2, 1, 0]
np.delete(x, 0,)

array([0, 0, 1, 2, 3, 0, 2, 1, 0])

array([1, 2, 3, 0, 2, 1])